# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Machine.create([
  { :model => "KM1820", :toner_id => 1, :created_at => "2013-03-08 05:24:45", :updated_at => "2013-03-08 05:24:45" },
  { :model => "KM4050", :toner_id => 2, :created_at => "2013-03-08 05:37:48", :updated_at => "2013-03-08 05:37:48" },
  { :model => "KM3050", :toner_id => 2, :created_at => "2013-03-08 05:38:05", :updated_at => "2013-03-08 05:38:05" },
  { :model => "KM5050", :toner_id => 2, :created_at => "2013-03-08 05:38:19", :updated_at => "2013-03-08 05:38:19" },
  { :model => "FS1028", :toner_id => 3, :created_at => "2013-03-08 05:40:01", :updated_at => "2013-03-08 05:40:09" },
  { :model => "FS1128", :toner_id => 3, :created_at => "2013-03-08 05:40:23", :updated_at => "2013-03-08 05:40:23" }
], :without_protection => true )



Toner.create([
  { :name => "TK18", :yield => 6000, :created_at => "2013-03-08 05:12:57", :updated_at => "2013-03-08 05:12:57" },
  { :name => "TK717", :yield => 34000, :created_at => "2013-03-08 05:36:08", :updated_at => "2013-03-08 05:36:21" },
  { :name => "TK132", :yield => 7200, :created_at => "2013-03-08 05:39:44", :updated_at => "2013-03-08 05:39:44" }
], :without_protection => true )


